import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout';

export default function Home() {
  return (
    <Layout Home>
    <>

    <div className={styles.container}>
      <Head>
        <title>Week 6</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Week 6 project
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://cs5513-week06-dk6.srjcethanwilde.repl.co/resources/0C6gkzvkhFTA6iaGCGp1" className={styles.card}>
            <h2>Browser Compatibility? &rarr;</h2>
          </a>

          <a href="https://cs5513-week06-dk6.srjcethanwilde.repl.co/resources/nK5oMKYRadfvqQQOOtxN" className={styles.card}>
            <h2>Describe Things &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    </>
    </Layout>
  )
}
